### ISSUE TITLE
🧐[问题] StatisticCard 中statistic的 valueStyle 如何引用less文件中定义的样式

### ISSUE THREAD

**Issue by fanhualei** [ant-design/pro-components#2467]
### 🧐 问题描述

# StatisticCard 中statistic的 valueStyle 如何引用less文件中定义的样式

> 例如下面的代码，想实现antDesignPro中的样式

``` tsx
      <StatisticCard
        statistic={{
          title: <Title title="总销售额" desc="指标说明" />,
          value: 126560,
          valueStyle,
          prefix: '¥',
          description: (
            <Space>
              <Statistic title="实际完成度" value="82.3%" />
              <Statistic title="当前目标" value="¥6000" />
            </Space>
          ),
        }}
        style={{ width: 268 }}
      />

```

> 在index.less 中这么定义

```less
.total {
  height: 38px;
  margin-top: 4px;
  margin-bottom: 0;
  overflow: hidden;
  color: @heading-color;
  font-size: 30px;
  line-height: 38px;
  white-space: nowrap;
  text-overflow: ellipsis;
  word-break: break-all;
}
```

# 如何引用index.less 中的 totla呢？

下面的做法会报错
```tsx
import styles from './index.less';

valueStyle: styles.total

```

> 现在只能定义一个变量
```tsx
const valueStyle: React.CSSProperties = {
  height: 38,
  marginTop: 4,
  marginBottom: 0,
  overflow: 'hidden',
  fontSize: 30,
  fontWeight: 450,
};
```

但是这样却引用不了 @import '~antd/es/style/themes/default.less'; 中的变量了
