### ISSUE TITLE
🐛[BUG]ProFormSelect组件只读模式下的展示问题

### ISSUE THREAD

**Issue by GJW666888** [ant-design/pro-components#5076]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProFormSelect组件多选模式下设置为只读的时候，会导致展示的每一个选中的label展示的时候挤压，成为竖排

### 📷 复现步骤

按照描述可以复现这个问题，需要注意的是在溢出这一行的时候，数据越多，问题越明显

### 🏞 期望结果

期望当溢出的时候，展示的只读数据可以换行展示

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本 ^3.1.2
- 浏览器环境 谷歌浏览器
- 开发环境 [e.g. mac OS]

**Comment by 15723185734** [comment]
不出一个dom根本不知道你在讲什么

**Comment by GJW666888** [comment]
![Uploading image.png…]()
本地写了个demo，可以参考的砍下效果

**Comment by GJW666888** [comment]
<img width="1680" alt="截屏2022-04-25 11 25 12" src="https://user-images.githubusercontent.com/66716790/165015838-04e17327-3785-4483-946e-76075a79244f.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


感谢提供截图和详细信息，这个问题是 ProFormSelect 组件只读模式下多选选项超出一行时，选中的 label 显示异常的问题。可以采用以下方式解决：

1. 升级 ProComponents 版本到最新版，是否已经修复了该问题，可以参考 ProComponents 的发布记录。

2. 通过 CSS 样式对 label 进行换行控制。可以设置 label 的样式为 `display: block; white-space: normal; word-wrap: break-word;`，这样可以让 label 换行显示，避免挤压的问题。具体代码如下：

```css
.pro-form-static .pro-field-read-content [class$="-value-item"] .ant-tag,
.pro-form-static .pro-field-label [class$="-value-item"] .ant-tag {
    display: block;
    white-space: normal;
    word-wrap: break-word;
    margin-bottom: 2px;
}
```

这里需要注意，需要将样式加上 `.pro-form-static` 类名，这样才能针对只读模式下的的 label 控制样式。同时需要注意样式的选择器是否与其他地方的样式产生冲突，需要根据具体情况进行调整。

希望能够帮助到你解决问题。
