### ISSUE TITLE
使用Protable ellipsis属性移动端会出现显示问题

### ISSUE THREAD

**Issue by changlin0501** [ant-design/pro-components#5397]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🧐 问题描述

使用Protable ellipsis属性移动端会出现显示问题

### 🚑 其他信息

antd : 4.21.2
react: 17.0.0

**Comment by changlin0501** [comment]
![image](https://user-images.githubusercontent.com/47729295/174253156-9b934679-ea08-4f80-97e8-cbfaba2bad04.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


根据您提供的截图，可以发现是由于 `ellipsis` 属性引起的问题。在移动端，文字过长会被省略号 `...` 替换，应用 `ellipsis` 属性时，而这可能导致文字显示不全。

这种情况下，可以尝试调整 CSS 样式来解决。例如，可以增加 `line-height` 属性，以调整行高，在移动端可以更好地展示省略号。也可以使用 `word-break` 属性来改变单词折行方式。

参考代码如下：

```css
.ant-pro-table-cell-ellipsis {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  line-height: 1.5; /* 调整行高 */
  word-break: break-all; /* 或者改变单词折行方式 */
}
```

另外，强烈建议您在使用 `ProTable` 的时候配合使用 `antd` 提供的 `responsive` 属性，定义不同设备下的列配置。这样可以更好地适配移动端的展示效果。

```jsx
<ProTable
  columns={columns}
  dataSource={data}
  // responsive 定义不同设备下的列配置
  responsive={{
    xs: 1, // < 768px 展示一列
    sm: 2, // >= 768px 展示两列
    md: 3, // >= 992px 展示三列
    lg: 4, // >= 1200px 展示四列
    xl: 5, // >= 1600px 展示五列
    xxl: 6, // >= 1920px 展示六列
  }}
/>
```

如果以上解决方案无法解决您的问题，建议您参考 ProTable 官方文档，或者提供更详细的代码和截图以便于分析问题。
