### ISSUE TITLE
🐛[BUG] ProLayout v6 菜单高度间距不一致

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#5735]
![image](https://user-images.githubusercontent.com/3166799/185145000-1722d5a3-4c51-4e5d-80b9-1331a7e9a509.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，针对你的问题，我们推荐如下解决方案：

1.检查菜单项的高度是否一致，可以通过以下代码检查：

```javascript
  const menuDataRender = (menuList) => {
    return menuList.map((item) => {
      if (item.children) {
        return { ...item, children: menuDataRender(item.children) };
      }
      return {
        ...item,
        height: document.getElementById(item.key).offsetHeight,
      };
    });
  };
```

2.对于高度问题，可以尝试通过CSS样式调整解决，比如对于菜单项，可以设置为：

```css
.ant-menu:not(.ant-menu-horizontal) .ant-menu-item,
.ant-menu-submenu-popup .ant-menu-item {
  height: 48px;
  line-height: 48px;
}
```

3.如果以上方法仍然无法解决你的问题，可以向Ant Design Pro的Github仓库中提交issue，获取更多资源和支持。

希望这个回答能够帮助你解决问题。
