### ISSUE TITLE
🐛[BUG] ProTable工具栏的加载动画样式有问题。

### ISSUE THREAD

**Issue by ldwonday** [ant-design/pro-components#6274]
如题，工具栏刷新图标的动画样式打包后如下：
```css
  :where(.css-4sxmcs).ant-pro-table-polling
    .ant-pro-table-list-toolbar-setting-item
    .anticon.anticon-reload {
    transform: rotate(0deg);
    animation-name: turn;
    animation-duration: 1s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
  }

// @keyframes turn {
  //   0:where(.css-4sxmcs)% {
  //     transform: rotate(0deg);
  //   }
  //   25:where(.css-4sxmcs)% {
  //     transform: rotate(90deg);
  //   }
  //   50:where(.css-4sxmcs)% {
  //     transform: rotate(180deg);
  //   }
  //   75:where(.css-4sxmcs)% {
  //     transform: rotate(270deg);
  //   }
  //   100:where(.css-4sxmcs)% {
  //     transform: rotate(360deg);
  //   }
  // }
```

这个keyframes语法是错误的，导致浏览器不能识别。

<img width="383" alt="企业微信截图_62d16923-5775-4a2b-9721-2397e5d7366f" src="https://user-images.githubusercontent.com/4630157/203889105-21ccdbb2-ce4e-4422-9a80-df703347dfef.png">

在作为子应用时会抛出异常
<img width="596" alt="企业微信截图_52d9074e-c146-486c-9b44-c71e04eab341" src="https://user-images.githubusercontent.com/4630157/203889465-b87a0ec8-ac3d-4f08-893e-03e94c200c4c.png">
