### ISSUE TITLE
🐛[BUG] ProDescriptions loading 样式无法自定义

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/pro-components#6295]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

ProDescriptions loading 样式无法自定义

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 可能的原因

由于 ProDescriptions 的 loading 样式是通过调用 antd 的 Spin 组件实现的，而 antd 的 Spin 组件并没有提供直接自定义样式的功能，因此 ProDescriptions 的 loading 样式也无法直接自定义。

### 解决方案

#### 方案一：

通过自定义样式来覆盖 antd 的 Spin 样式，从而改变 ProDescriptions 的 loading 样式。具体步骤如下：

1. 在组件所在的样式文件（一般是.less 或 .css 文件）中，定义覆盖 antd Spin 样式的新样式，例如：

```css
.custom-spin {
  display: inline-block;
  width: 20px;
  height: 20px;
  vertical-align: middle;
  border-radius: 50%;
  border: 2px solid #ccc;
  border-top-color: #999;
  animation: custom-spin 0.6s linear infinite;
}

@keyframes custom-spin {
  to {
    transform: rotate(360deg);
  }
}
```

2. 在 ProDescriptions 组件上加上 loadingIndicator 属性，并指定该属性的值为新样式的类名，例如：

```jsx
<ProDescriptions
  // ...其他属性
  loadingIndicator={<span className="custom-spin" />}
>
  {/* ... */}
</ProDescriptions>
```

#### 方案二：

自定义 ProDescriptions 组件，并在其内部覆盖 antd Spin 样式。具体步骤如下：

1. 在你的项目中创建一个新的组件，例如 CustomProDescriptions。

2. 在 CustomProDescriptions 组件中引入 ProDescriptions 和 Spin 组件，例如：

```jsx
import { ProDescriptions, Spin } from 'antd';
```

3. 在 CustomProDescriptions 组件的样式文件（一般是.less 或 .css 文件）中，定义覆盖 antd Spin 样式的新样式，并在 Spin 上加上该样式，例如：

```css
.custom-spin {
  // ...自定义样式
}

.ant-spin .custom-spin {
  // ...覆盖 antd Spin 样式
}
```

4. 在 CustomProDescriptions 组件中覆盖 antd Spin 组件，并加上自定义样式，例如：

```jsx
const CustomSpin = () => <Spin className="custom-spin" />;

const CustomProDescriptions = (props) => {
  const { loading } = props;

  return (
    <ProDescriptions
      // ...其他属性
      loadingIndicator={<CustomSpin />}
      loading={loading}
    >
      {/* ... */}
    </ProDescriptions>
  );
};
```

5. 在自己的项目中使用 CustomProDescriptions 组件，例如：

```jsx
<CustomProDescriptions
  // ...其他属性
  loading={true}
>
  {/* ... */}
</CustomProDescriptions>
```

### 参考文档

- [antd Spin 组件](https://ant.design/components/spin-cn/)
- [覆盖 antd 组件样式](https://ant.design/docs/react/customize-theme-cn#在less变量中覆盖组件样式)
