### ISSUE TITLE
🐛[BUG] ':where(...) *' selectors clash with my styles and third-party libraries

### ISSUE THREAD

**Issue by neongreen** [ant-design/pro-components#6419]
I understand that `:where` selectors in the theme are supposed to have lower priority, but they still clash with my styles thanks to the `*` bit afterwards.

For example, I have:

```css
code { font-family: Iosevka !important }
```

And then I have `<code><u>blah</u></code>` inside a `ProList`.

For the `<u>` element inside the `<code>` element, the priority of rules is as follows:

```css
/* higher priority */
:where(.css-1bfxm4t).ant-pro-card * {
  box-sizing: border-box;
  font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,
      'Helvetica Neue',Arial,'Noto Sans',sans-serif,'Apple Color Emoji',
      'Segoe UI Emoji','Segoe UI Symbol','Noto Color Emoji';
}

/* lower priority */
code { font-family: Iosevka!important; }
```

As the result, for `<code><u>...</u></code>` my styles don't apply.

Same happens with libraries like KaTeX.

Is `*` necessary there? Without it, things seems to work fine.
