### ISSUE TITLE
🐛[BUG]  PageContainer在暗黑模式下fixedHeader背景颜色不正确

### ISSUE THREAD

**Issue by mwj610** [ant-design/pro-components#6610]
"@ant-design/pro-components": "^2.3.54"

正常主题：
![image](https://user-images.githubusercontent.com/52907799/218948352-742e76d2-32e3-4271-9d1f-c4dd84a29304.png)
黑色主题：
![image](https://user-images.githubusercontent.com/52907799/218948300-cec36c8d-744d-44b3-bf78-0f51ce4705b9.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


你好，根据你提供的信息，你的问题是在 Ant Design Pro 中，使用 PageContainer 组件时，在暗黑模式下使用 fixedHeader 属性时，背景颜色不正确。

针对这个问题，可以尝试以下解决方案：

1. 自定义主题颜色

在 Ant Design Pro 中，支持自定义主题颜色。可以在 `config.less` 文件中自定义项目的主题颜色。具体操作可参考文档：https://pro.ant.design/docs/theme-cn。

2. 使用 CSS 样式修改背景颜色

在 `src/locales/zh-CN/layout.ts` 文件中，PageContainer 的 fixedHeader 在暗黑模式下的样式为：

```css
.ant-pro-fixed-header {
  background-color: @ant-design-pro-layout-content-background;
  border-bottom: 1px solid @ant-design-pro-layout-header-border-color;
  padding: 0 24px;
  z-index: 999;
  transition: all 0.3s;
}
```

可以通过在 `src/global.less` 文件中覆盖该样式，修改 fixedHeader 的背景颜色。例如：

```css
/* 暗黑模式下，修改 fixedHeader 的背景颜色 */
body[data-theme='dark'] .ant-pro-fixed-header {
  background-color: #1f1f1f;
}
```

3. 提交 Issue

如果以上方案无法解决问题，请尝试提交 Issue 到 Ant Design Pro 仓库中，以获得更好的支持：https://github.com/ant-design/ant-design-pro/issues。

希望以上方案能对你有所帮助。
