### ISSUE TITLE
🐛[BUG] 升级Antd5以后，样式LoginForm出现样式层级问题

### ISSUE THREAD

**Issue by Nicolana** [ant-design/pro-components#6653]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
![image](https://user-images.githubusercontent.com/20972473/220879790-909cde1e-b813-4ee2-92e6-cc973081bf8d.png)
可以直接看到，prefix的图标已经从16px变成了14px
![image](https://user-images.githubusercontent.com/20972473/220879991-21b47413-7f93-4317-810f-98f0afd598ed.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


您好，根据您提供的信息，似乎是Antd升级到5版本后，表单中的图标大小发生了变化。这可能是由于Antd 5版本对CSS样式层级优化所致导致的，因此您可以手动指定样式层级以覆盖默认的样式。

以下是一个可能的解决方案，您可以在样式表中添加以下CSS规则：

```css
.ant-form-item-label > .anticon:before {
  font-size: 16px !important; /* 指定图标大小 */
  margin-right: 8px; /* 指定图标右边距离表单项的距离 */
}
```

其中，`.ant-form-item-label` 和 `.anticon:before` 分别代表 Antd 表单项的标签和图标区域。

此外，您可能还需要考虑指定其他相关的样式，以更好地符合您的设计需求。

另外，您可以参考 Antd 官方文档：https://ant.design/components/form-cn/#components-form-demo-login ，以获取有关如何使用 Antd 表单组件的更多信息。

希望这可以帮到您！
