### ISSUE TITLE
🐛[BUG] CheckCard size="large" is not responsive.

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#6753]
### 🐛 bug 描述
When the CheckCard size value is set to large, it takes a fixed value of 440px.
ant-pro-checkcard-lg
当 CheckCard size 值设置为 large 时，它取固定值 440px。

### 📷 复现步骤
![image](https://user-images.githubusercontent.com/6988989/224020792-29df677f-c907-4f8d-bb3c-6739c4db3709.png)

### © 版本信息

    "@ant-design/charts": "^1.4.2",
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "1.1.25",
    "@ant-design/pro-field": "^2.3.0",
    "@ant-design/pro-list": "^1.21.64",
    "umi": "^3.5.0",
- 浏览器环境
- 开发环境 [e.g. mac OS] : Windows 11, Chrome latest version.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 解决方案
这个问题可能是由于 CheckCard组件的样式设置宽度时使用了固定宽度值，而不是使用百分比或rem等相对单位，导致在弹性布局中不起作用。以百分比为单位可以使组件的大小更加灵活和响应式。

可以通过在设置宽度时使用百分比来解决此问题，例如：将`width: 440px`（原楼主提供的代码截图中显示的样式）更改为`width: 100%`。

```css
.ant-pro-checkcard-lg .ant-card {
  width: 100%;
}
```

此外，还可以考虑响应式设计的方式，使用媒体查询来根据设备屏幕宽度调整 CheckCard 组件的大小，例如：

```css
@media (max-width: 768px) {
  .ant-pro-checkcard-lg .ant-card {
    width: 100%;
  }
}
```

这样可以使 CheckCard 在移动设备上也能够正常显示，并保持响应式。

### 参考文档
- [Ant Design Pro - CheckCard](https://procomponents.ant.design/components/check-card-cn/)
