### ISSUE TITLE
👑 [需求]如何让ProForm.Group的title和包裹元素一行显示？

### ISSUE THREAD

**Issue by Connor-lipalater** [ant-design/pro-components#6778]
🥰 需求描述：
如何让ProForm.Group的title和包裹元素一行显示，如下图表单，Phone number这一行使用了ProForm.Group组件包裹了两个组件，但是这一行和上下格式不一致，期望title可以和输入框一行显示，并且对齐。
？
效果如下：
![image](https://user-images.githubusercontent.com/105040671/224942461-414e06be-65cc-4c20-a890-42080932ce39.png)

代码图如下：
![image](https://user-images.githubusercontent.com/105040671/224942920-6222358b-44eb-4c21-928e-0e208c99ca3c.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。




✨ 解决方案：

可以通过CSS样式来调整ProForm.Group中title和包裹元素的显示位置。方法如下：

1. 给ProForm.Group添加一个自定义的className属性，例如"custom-group"。
2. 在CSS样式文件中添加以下代码：

```css
.custom-group .ant-form-item-label {
  display: inline-block;
  width: 110px;  /* 根据实际情况进行调整 */
}
.custom-group .ant-form-item-control {
  display: inline-block;
}
```
其中，通过将.ant-form-item-label和.ant-form-item-control的display属性设置为inline-block，可以让它们在同一行显示。通过为.ant-form-item-label设置固定的宽度，可以控制title和输入框的对齐效果。

自定义className属性的方法可参考ProForm的官方文档。

参考文档：
- [ProForm文档中的自定义className属性](https://procomponents.ant.design/components/table/#classnamedivider)
- [Ant Design的样式控制](https://ant.design/components/style-cn/)
