### ISSUE TITLE
🐛[BUG] 菜单收起展开，logo上方出现菜单文字

### ISSUE THREAD

**Issue by yao378186268** [ant-design/pro-components#6791]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述
菜单展开的时候，logo上方会出现隐藏菜单文字。

### 📷 复现步骤
1、在ProCompopnents官方文档中，找到ProLayout 组件第一个 demo，在独立页面打开。
2、右侧设置按钮，勾掉 自动分割菜单。
3、重复点击 菜单折叠收起的 icon，左上角 logo 上方会闪烁出现菜单文字。

### 🏞 期望结果
展开菜单，不出现闪烁文字

### © 版本信息

- ProComponents 版本: v2.4.2
- umi 版本
- 浏览器环境: Chrome
- 开发环境：window

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/84838562/225557597-e202b2e6-da8c-4a70-a6b6-29da2c6d3906.png)
![37e1c063183008c14f0b65216f55806](https://user-images.githubusercontent.com/84838562/225557968-ab7df228-886f-4c9a-b0ff-280833b4cff8.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，根据你提供的信息，可能是一些 CSS 样式没有正确处理导致，可以按照以下步骤来解决该问题：

1. 在页面加载后查看菜单展开时所额外添加的文本元素，并设置其样式为 `display: none;`，例如：

```css
.ant-layout-sider-collapsed .logo_text {
  display: none;
}
```

2. 确保你的自定义 logo 元素样式正确设置，例如：

```css
/* 正常展开时 logo 元素 */
.logo {
  height: 32px;
  background: rgba(255, 255, 255, 0.2);
  margin: 16px;
}

/* 折叠时的 logo 元素 */
.ant-layout-sider-collapsed .logo {
  margin: 16px 6px;
  width: 48px;
  height: 48px;
}

/* logo 元素中插入的文本元素样式 */
.logo_text {
  color: #fff;
  font-size: 22px;
  margin-left: 12px;
  display: inline-block; /* 确保文本元素能够正确显示 */
}
```

3. 通过修改 `.ant-layout-sider` 的样式控制文本元素的位置，例如：

```css
.ant-layout-sider {
  position: relative; /* 确保定位正常 */
}

.ant-layout-sider-collapsed.ant-layout-sider-has-trigger .ant-layout-sider-trigger {
  position: absolute; /* 确保 icon 位置正常 */
  bottom: 0;
  left: 0;
  z-index: 1000; /* 确保文本元素在下层 */
}

.ant-layout-sider-collapsed.ant-layout-sider-has-trigger .logo_text {
  position: absolute; /* 确保文本元素位置正常 */
  bottom: 0;
  margin-left: 24px; /* 和 antd 的默认行为一致，icon 和文本相隔 24px */
  z-index: 999; /* 确保在 icon 上层 */
}
```

参考文档：

- [ProLayout API](https://procomponents.ant.design/components/layout/#props)
- [Ant Design Layout Sider 组件](https://ant.design/components/layout-cn/#Layout.Sider)
