### ISSUE TITLE
🐛[BUG] 官网升级 2.4.3 版本后， PorLayout显示不全

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#6883]
### 🐛 bug 描述
https://procomponents.ant.design/components/layout?tab=api#packages-layout-src-components-layout-tab-api-demo-sidermode
![image](https://user-images.githubusercontent.com/29336835/229441527-652c71a1-8e98-436f-87b7-07d3b5659a77.png)

### © 版本信息

- ProComponents 版本: 2.4.3
- umi 版本 4
- 浏览器环境 Chrome 111.0.5563.147（正式版本)
- 开发环境  win11

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


您好，感谢您提供的信息。根据您提供的信息和截图，您可能遇到了 Ant Design Pro 的 Layout 组件在 2.4.3 版本下出现的一个已知问题，即在 Sider mode 为 `inline` 时，部分 Sider 隐藏的情况下，Content 区域的宽度计算不正确。这可能会导致 Content 区域显示不全或者布局错乱。

目前，该问题已被修复并发布到最新版本(2.5.5)，您可以通过升级到最新版本解决该问题。

如果您无法升级，您可以手动修改 ProLayout 组件的 CSS，增加一个宽度计算的判断，以保证 Content 区域的宽度显示正确。例如：

```css
.pro-menu {
  &&& {
    .ant-menu-inline {
      /* 增加此判断：当 Sider 隐藏时，Content 区域宽度为 100% */
      &:not(.ant-menu-hidden) {
        width: calc(100% - var(--pro-sider-width));
        margin-left: var(--pro-sider-width);
      }
      &:not(.ant-menu-hidden).ant-menu-sub {
        margin-left: calc(var(--pro-sider-width) + var(--submenu-inline-indent));
      }
    }
  }
}
```

同时，建议您参考官方文档，了解 Ant Design Pro Layout 组件的使用方式和属性：https://procomponents.ant.design/components/layout/。

希望能对您有所帮助。如有其他问题或疑问，请随时联系我。
