### ISSUE TITLE
🐛[BUG] 二级菜单和一级菜单的文字部分未对齐

### ISSUE THREAD

**Issue by Gzbox** [ant-design/pro-components#6907]
### 🐛 bug 描述

当有二级菜单时，感觉二级菜单不显示icon,也应该和一级菜单的文字对齐，现在是不对齐的，具体情况请看截图

### 🏞 期望结果

希望文字部分能够对齐

### © 版本信息

- ProComponents 版本："^2.4.4",
- umi 版本："^4.0.64",
- 浏览器环境：111.0.5563.146（正式版本） (x86_64)
- 开发环境：mac OS

### 🚑 其他信息

<img width="253" alt="image" src="https://user-images.githubusercontent.com/21010051/230575294-ee93d0ab-d50d-4ea3-93b1-7cfcc3fa75a2.png">

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 解决方案

这个问题可能是由于antd-pro自带的样式没有完全覆盖，可以使用CSS来解决。你可以在你的CSS文件中添加以下代码：

```css
.ant-menu-submenu-title {
  display: flex;
  align-items: center;
}
.ant-menu-submenu-arrow {
  margin-left: auto;
}
```

这将使所有子菜单标题与对应的图标对齐，同时将箭头移到文本的右侧。

如果你没有单独的CSS文件，可以在`<style>`标签中添加这些样式。

此外，你还可以参考antd-pro[官方文档](https://pro.ant.design/docs/style-cn)，查看更多的样式定制选项。

希望对你有所帮助！
