### ISSUE TITLE
🐛[BUG] 当右侧内容区域出现滚动条的时候，头像下拉框无法显示。官网例子也有这个问题

### ISSUE THREAD

**Issue by pc110** [ant-design/pro-components#6911]
### 🐛 bug 描述
没有滚动条“退出登录”正常显示
![8ef5d8327099c9f893da39ca03426c7](https://user-images.githubusercontent.com/29336835/230767922-a9b7ad7d-8df6-45d9-8d3c-1be5576d4085.png)

有滚动条，“退出登录” 无法显示
![9238561690dd6149291d3bf470eb5f5](https://user-images.githubusercontent.com/29336835/230767925-fb71c4f8-42f4-40b4-8cc1-d0dbb71686a6.png)

官网例子，鼠标放在头像上，滚动鼠标，退出登录位置发生改变

![1681036806703](https://user-images.githubusercontent.com/29336835/230767982-1fb85138-ec2f-4cfe-bb30-71246c7f264d.png)

### © 版本信息

- ProComponents 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


这个问题可能是由于头像下拉框使用了固定定位导致的，当内容区域出现滚动条时，固定定位的元素的位置可能会受到影响。

解决方案可以考虑去掉头像下拉框的固定定位，改用绝对定位，并在父元素上设置相对定位。

HTML部分示例代码：

```html
<div class="avatar-box">
  <img src="avatar.jpg">
  <ul class="dropdown">
    <li>个人资料</li>
    <li>退出登录</li>
  </ul>
</div>
```

CSS部分示例代码：

```css
.avatar-box {
  position: relative;  /* 父元素相对定位 */
}

.avatar-box img {
  width: 50px;
  height: 50px;
  border-radius: 50%;
}

.avatar-box .dropdown {
  position: absolute;  /* 头像下拉选项绝对定位 */
  top: 55px;
  right: 0;
  z-index: 1;
  background-color: white;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  list-style: none;
  padding: 0;
  margin: 0;
}

.avatar-box .dropdown li {
  padding: 12px 24px;
  cursor: pointer;
}

.avatar-box .dropdown li:hover {
  background-color: #f5f5f5;
}
```

更多关于绝对定位和相对定位以及固定定位的知识可以参考MDN的文档：https://developer.mozilla.org/zh-CN/docs/Web/CSS/position
