### ISSUE TITLE
👑 [需求]StatisticCard指标 设计和字体设计

### ISSUE THREAD

**Issue by hexiaomin496** [ant-design/pro-components#6941]
### 🥰 需求描述

请问StatisticCard 针对指标字体大小的设计已经确定为fontSize: 40了吗？

感觉和之前的设计不太一样了。

### 🚑 其他信息
![image](https://user-images.githubusercontent.com/23149314/231997056-a824309e-53a0-4564-b80d-101f74fee7b4.png)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


你好，首先回答你的问题，关于 `StatisticCard` 默认的字体大小是 `fontSize: 40`，如果你希望调整字体大小，可以通过修改 `fontSize` 来实现。

至于你提到的是否支持原来的样式选择，我需要了解更多的背景信息才能给出明确的答复。可以提供一下你希望被支持的样式选择和原来的代码实现，我会尽可能地提供帮助。

此外，如果你希望自定义 `StatisticCard` 样式，可以在组件中使用 `className` 自定义样式名称，然后在 CSS 中定义相应的样式。以下是一个示例代码：

```jsx
import React from 'react';
import { Statistic } from 'antd';
import './custom-statistic-card.css';

const CustomStatisticCard = () => (
  <div className="custom-statistic-card">
    <Statistic title="Active Users" value={112893} />
  </div>
);

export default CustomStatisticCard;
```

```css
.custom-statistic-card .ant-statistic-title {
  font-size: 20px;
  font-weight: bold;
  color: #1890ff;
}
.custom-statistic-card .ant-statistic-content {
  font-size: 36px;
  font-weight: bold;
  color: #52c41a;
}
```

在 CSS 中使用 `custom-statistic-card` 定义组件自定义 class 名称，然后实现相应的样式即可。
