### ISSUE TITLE
🧐[问题]table toolbar 标题过长后，出现...，但是鼠标移上去没有显示全部标题

### ISSUE THREAD

**Issue by xian107** [ant-design/pro-components#8007]
table toolbar 标题过长后，出现...，但是鼠标移上去没有显示全部标题，请问怎么才能显示？哪怕加个title属性也行
![image](https://github.com/ant-design/pro-components/assets/13252682/5a39452b-7289-4596-81c7-d4fc0ddd6aa8)
![image](https://github.com/ant-design/pro-components/assets/13252682/b5da811b-a8f6-40c2-8b52-6a7ded249bd1)

**Comment by chenshuai2144** [comment]
根据您提供的片段，问题是在表格工具栏中，标题过长时会出现省略号，但鼠标移上去没有显示全部标题。

这个问题可能是由于CSS中的文本溢出导致的。默认情况下，表格工具栏的标题没有设置溢出显示的样式，所以当标题过长时会被省略号替代，并且鼠标移上去没有显示全部标题。

解决这个问题的方法是在标题所在的元素上添加样式，指定文本溢出的处理方式。例如，可以使用`text-overflow: ellipsis`属性来实现省略号的显示，并且在鼠标移上去时显示全部内容。

具体的代码示例如下所示：

```css
.toolbar-title {
  white-space: nowrap; /* 不换行 */
  overflow: hidden; /* 溢出部分隐藏 */
  text-overflow: ellipsis; /* 超出部分显示省略号 */
}

.toolbar-title:hover {
  overflow: visible; /* 鼠标移上去显示全部内容 */
}
```

您需要将上述样式应用到表格工具栏标题所在的元素中，例如使用`class="toolbar-title"`来指定这个样式。

希望这个解决方案可以帮助您解决问题！如果还有其他问题，请随时提问。
