### ISSUE TITLE
ProComponent 3.0 路线图

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/pro-components#8178]
2023 年 02 月 发布 ProComponent 2.0  之后，我们一直在做着兼容 antd@4  和  antd@5  的工作，随着时间的推进，2022 年 11 月发布的 antd5 覆盖率已经超过了百分之 60，最近社区也做了一份文件调查，72% 的用户也已经升级到了  antd@5。ProComponent 也是时候轻装上阵去掉 antd@4  的支持来换取更小的包大小，更好的试用体验。

![image.png](https://cdn.nlark.com/yuque/0/2024/png/84868/1708493784335-85b95620-4871-4b27-81df-9f0988c98b45.png#averageHue=%23bddceb&clientId=u0ef4f100-df2d-4&from=paste&height=383&id=ueaa94c08&originHeight=766&originWidth=1718&originalType=binary&ratio=2&rotation=0&showTitle=false&size=839514&status=done&style=shadow&taskId=u36441f43-bd00-43c9-9b9c-67b99cdc13d&title=&width=859)

3.0  中我们主要会做的以下的一些非兼容性操作

- 去除 antd@4 的兼容性
- 优化包大小和性能

## 🗑 去除 antd@4  的兼容性
为了兼容 antd@4  我们增加了一些适应性的代码，例如
```
// 兼容性代码
import 'antd/lib/list/style';
```
这样的代码会导致在线上多导入一份 css，在 5.0  中我们可以去掉它，另外还有一系列的 compareVersions 代码，我们将会全部与最新的 antd5 进行兼容不再兼容旧版本 antd。
![image.png](https://cdn.nlark.com/yuque/0/2024/png/84868/1708494109332-502ccbeb-a3b9-4620-8542-d07a58cc63f9.png#averageHue=%233c627f&clientId=u0ef4f100-df2d-4&from=paste&height=617&id=u3dd0b766&originHeight=1234&originWidth=956&originalType=binary&ratio=2&rotation=0&showTitle=false&size=219218&status=done&style=shadow&taskId=u9161128f-dba4-40b5-b398-405172bc711&title=&width=478)

另外为了兼容我们无法试用  antd 的新特性 ，例如  ColorPicker 和  Flex 等组件，去除之后将会大大的减少包大小。

## 👜 优化包大小
由于  ProForm  的设计和  ValueType 的设计，我们默认绑定了一系列的组件进去，在引入一个组件的情况下就相当于引入了所有的组件，至少带来了  700k 的 gzip 大小。
![image.png](https://cdn.nlark.com/yuque/0/2024/png/84868/1708494737518-5f5dc5f6-189d-4362-9649-8a3b7371e893.png#averageHue=%23ac6bac&clientId=u0ef4f100-df2d-4&from=paste&height=626&id=u78c71ad6&originHeight=1252&originWidth=1431&originalType=binary&ratio=2&rotation=0&showTitle=false&size=443438&status=done&style=shadow&taskId=ub0e50732-38f6-46c2-bfcd-56061e32d66&title=&width=715.5)
3.0 我们会解决掉这个问题，完善 Tree Shaking 的问题。同时这样也能让性能提升不少。

## 📯 3.0 的规划
![image.png](https://cdn.nlark.com/yuque/0/2024/png/84868/1708495218569-bf8d5c88-025c-4aa8-9b11-d164d6e7f783.png#averageHue=%23bad9eb&clientId=u0ef4f100-df2d-4&from=paste&height=361&id=ud64f7dcb&originHeight=722&originWidth=1688&originalType=binary&ratio=2&rotation=0&showTitle=false&size=773115&status=done&style=shadow&taskId=u810d1140-4499-44d1-ba91-06ca0ddc652&title=&width=844)

基于问卷的数据和投入资源的取舍，未来会优先考虑功能性，确保组件的功能齐全、易用性强。同时也会关注性能方面，确保组件库在运行时的效率和性能表现。最受欢迎的  Form 组件同时也是问题最多的组件，在包大小优化中我们会优先解决  ProForm 的问题，为了  Form  带来更多会更好的特性。
同时对于性能比较堪忧的  ProTable  我们也会 进行一些性能的优化，性能基本像  antd  看齐。

### 问卷数据如下：
[ProComponents 新年调查(1-300).xlsx](https://www.yuque.com/attachments/yuque/0/2024/xlsx/84868/1708495454326-382f7877-5fcd-4162-88cd-4e1a75ff6a3c.xlsx)

如果你有任何其他的问题，欢迎在下方评论。

**Comment by leshalv** [comment]
给力

**Comment by faner11** [comment]
非常期待你们的工作，pro-component很好用，但是太重了，包大小问题一直是我比较头疼的问题

**Comment by asd116725** [comment]
干就完了，兄弟们

**Comment by bugfix2020** [comment]
期待

**Comment by chj-damon** [comment]
期待

**Comment by kaoding** [comment]
希望在API 上和antd 5.0 一致，设计上风格也保持和 5.0 一致

**Comment by echoyl** [comment]
期待

**Comment by lin-mt** [comment]
预计在什么时间点发布 3.0 呢

**Comment by fengzehao** [comment]
期待3.0，ProComponent超级好用

**Comment by xiaochong444** [comment]
会有表单设计器吗？

**Comment by oswayne** [comment]
我很喜欢 ProComponents，它非常的好用。期待 3.0 版本的到来。

**Comment by fnoopv** [comment]
会去掉rc-util依赖吗，`StrictMode` 的问题一直没处理，每次打开console都报错，看得难受

**Comment by imsunhao** [comment]
我很喜欢 ProComponents，它非常的好用。期待 3.0 版本的到来。

**Comment by luna825** [comment]
我很喜欢 ProComponents，它非常的好用。期待 3.0 版本的到来。

**Comment by rongxingsun** [comment]
能否增加一个select弹框选择器
![image](https://github.com/ant-design/pro-components/assets/12825624/b3ffef7b-6d1b-4b21-bd83-a11a5a721459)
可单选和多选
https://opentiny.design/tiny-vue/zh-CN/os-theme/components/popeditor

**Comment by Gzbox** [comment]
有新版的发布路线吗？

**Comment by wzbmail** [comment]
部分组件封装的request，建议格式统一，比如：modalForm的request 使用的是直接的响应内容，而Protable的request 使用的data的；
pro组件的样式尽量以ant design的组件样式为主，避免样式和antd不一致；
pro组件的token抛出来，允许像antd一样能更好的全局设置

**Comment by bxvs888** [comment]
3.0 什么时候可以发布？？？

**Comment by terwer** [comment]
奈斯，目前 react 下最好有的 UI 库，期待 3.0。

**Comment by mansion-sun** [comment]
1.SchemaForm 的JSON Schema 向ProTable的Columns 列定义看齐，实现像Column一样兼容，目前在列表中编辑的交互方式有一定局限性；更多的编辑可能是弹框表单或者新开页，如果能够将ProTable的Columns传递给SchemaForm 直接生成表单就更好了。
2.EditableProTable的性能优化，同时编辑多行时反应较慢和antd有一定差距；

**Comment by mansion-sun** [comment]
1.SchemaForm 的JSON Schema 向ProTable的Columns 列定义看齐，实现像Column一样兼容，目前在列表中编辑的交互方式有一定局限性；更多的编辑可能是弹框表单或者新开页，如果能够将ProTable的Columns传递给SchemaForm 直接生成表单就更好了。
2.EditableProTable的性能优化，同时编辑多行时反应较慢和antd有一定差距；

**Comment by mansion-sun** [comment]
1.SchemaForm 的JSON Schema 向ProTable的Columns 列定义看齐，实现像Column一样兼容，目前在列表中编辑的交互方式有一定局限性；更多的编辑可能是弹框表单或者新开页，如果能够将ProTable的Columns传递给SchemaForm 直接生成表单就更好了。
2.EditableProTable的性能优化，同时编辑多行时反应较慢和antd有一定差距；

**Comment by faner11** [comment]
> 'zustand'商店应提供支持。

这个是不能支持的,有人要redux，jotai, 众口难调

**Comment by xXAvoraXx** [comment]
> > 'zustand'商店应提供支持。
> 
> 这个是不能支持的,有人要redux，jotai, 众口难调

我认为 Redux 是一个笨重且过时的解决方案。

**Comment by piter902** [comment]
![image](https://github.com/user-attachments/assets/45a4f75a-826f-473d-a28f-dbfe27357a9b)
能否支持筛选组件中的操作按钮在第一行展示？

**Comment by 15607306950** [comment]
![image](https://github.com/user-attachments/assets/0a6cea0f-8333-49b1-8c1b-bc7b195da425)
能否支持筛选操作按钮在顶部展示？

**Comment by xXAvoraXx** [comment]
Can NextJs become compatible?
NextJs 能否兼容？

**Comment by conioX** [comment]
Any news about this?

**Comment by littlepoolshark** [comment]
pro-component是强大的。另外一面也意味着它配备了巨多的配置项。就当前而言，pro-component 的官方文档是并没有很好地把它的能力展现出来，使得用户在阅读完之后对它的能力一个充分的认知。所以，我建议把官网中 playground 这个板块的优化也放在 3.0 这个版本。可以使用实时的交互式编码的思想来重构一个这个板块。有同样需求的同学麻烦点一下，让官方看到社区的呼声。

**Comment by ldc2726** [comment]
还5.0呢，antd迭代也是非常迅速的，也带来了很多不一样的新特性。pro-component一不小心版本对不上就出来了很多问题。希望至少在5.20以后，样式冲突太大了！！！

**Comment by avivadepp** [comment]
能不能分点时间把已有bug修一修，感觉表单的好多功能都有问题

**Comment by wowtrxqn** [comment]
EditableProTable 还有很多bug， 官网的例子在线就有bug， 先修复bug，不然大家都用不了啊，这么多问题

**Comment by luna825** [comment]
3.0 今年会发布么？

**Comment by www3com** [comment]
同问

**Comment by mansion-sun** [comment]
> EditableProTable 还有很多bug， 官网的例子在线就有bug， 先修复bug，不然大家都用不了啊，这么多问题

有bug就提issue，把链接贴出来，没有证据就别抱怨；抱怨的话少说，这是开源项目，要懂得感恩。

**Comment by mansion-sun** [comment]
> EditableProTable 还有很多bug， 官网的例子在线就有bug， 先修复bug，不然大家都用不了啊，这么多问题

矮矮的

**Comment by chenJJ-88** [comment]
> > 3.0 今年会发布么？
> 
> 今年都没几天了，估计是难产了， pro 看起来只有一个人蚂蚁官方的人在维护，其他都是社区为爱发电了

大概率和 antd-pro 一样了

**Comment by 1029800858** [comment]
pro-component3.0发布了 踢我一脚

**Comment by liu245933567** [comment]
pro-component3.0发布了 也踢我一脚

**Comment by jinxiangqiang** [comment]
是等antd V6吗？都没怎么更新了

**Comment by weicong** [comment]
建议复刻 AntBlocks UI (https://www.antblocksui.com/)

**Comment by ideaviewes** [comment]
别再更新版本了，把bug都解决一下吧

**Comment by elkon028** [comment]
## 建议
1. 搜索栏添加 展开/收起 动画
2. 搜索栏 - actions 区域绝对定位在右上角
3. table 内容区域高度自适应能力
4.  table区域添加一个className(方便外部 css 选择器) , 否则我不得不用以下方案
  ```js
  tableRender={(_, dom) => <div className="plus-table-container">{dom}</div>}
  ```

<img width="1501" alt="Image" src="https://github.com/user-attachments/assets/2860d76c-37d8-4da1-9c57-32dc4c44f9cb" />

## 封装了一个 PlusTable
- src/components/ProSearchAnimation.tsx
```tsx
import type { MotionProps } from 'motion/react'
import type { JSX } from 'react'

import clsx from 'clsx'
import { motion } from 'motion/react'

interface Props extends MotionProps {
  children: JSX.Element
  className?: string
  /** 动画时长(秒) */
  duration?: number
  /** 是否收起 */
  collapsed?: boolean
}

const ProSearchAnimation: FC<Props> = memo(({ children, className, duration = 0.5 }) => {
  const resizeRef = useRef<HTMLDivElement>(null)
  const [height, setHeight] = useState(0)

  // 观察 resizeRef 的高度变化
  useEffect(() => {
    const resizeObserver = new ResizeObserver(entries => {
      for (const entry of entries) {
        setHeight(entry.contentRect.height)
      }
    })

    if (resizeRef.current) {
      resizeObserver.observe(resizeRef.current)
    }

    return () => {
      resizeObserver.disconnect()
    }
  }, [resizeRef])

  return (
    <motion.div
      animate={{ height }}
      className={clsx('pro-table-search-animate bg-card rounded', className)}
      transition={{
        duration
        // ease: [0.34, 2, 0.66, 1]
      }}>
      <div className="pro-table-search-animate--resize" ref={resizeRef}>
        {children}
      </div>
    </motion.div>
  )
})

export default ProSearchAnimation
```
- src/features/table/CollapseButton.tsx
```tsx
import clsx from 'clsx'

const CollapseButton = memo<{ collapsed: boolean; hiddenNum?: number | false }>(({ collapsed, hiddenNum }) => {
  const count = hiddenNum && hiddenNum > 0 ? hiddenNum - 1 : undefined
  return (
    <ABadge count={count} size="small">
      <AButton
        icon={
          <SvgIcon
            className={clsx('transition-all duration-500', { 'rotate-90': !collapsed })}
            icon="solar:double-alt-arrow-right-line-duotone"
          />
        }
      />
    </ABadge>
  )
})

export default CollapseButton

```
- src/features/table/index.tsx
```tsx
import type { ActionType, ProColumns, ProFormInstance, ProTableProps } from '@ant-design/pro-components'

import { ProTable } from '@ant-design/pro-components' // TableDropdown
import { ConfigProvider, Table, theme } from 'antd'

import CollapseButton from './CollapseButton'

import { themeColors, useTheme } from '@/features/theme'
import { getAntdTheme } from '@/features/theme/shared'
import { useThemeSettings } from '@/features/theme/themeHook'
import { waitTime } from '@/utils'

export type { ActionType, ProColumns, ProTableProps }

type DataRow = Record<string, any>
type TableProps<T extends DataRow> = {
  api: (...args: any) => Promise<any>
  /** 是否显示边框 */
  border?: boolean
  /** 表格列配置 */
  columns: ProColumns[]
  /** 是否compact模式 */
  compact?: boolean
  /** 是否分页 */
  pagination?: boolean
  /** 接口附加的参数 */
  params?: Recordable
  /** 行键名 */
  rowKey?: keyof T | string
  /** 表格标题 */
  title?: string
  /** 搜索表单列数 */
  searchFormCols?: number
}

const spacer: ProColumns = {
  title: '占位列',
  dataIndex: '_SPACER_',
  search: true,
  hideInDescriptions: true,
  hideInSetting: true,
  hideInTable: true,
  formItemProps: { className: 'hidden' },
  renderFormItem: () => <div>渲染一个占位列</div>
}

function useAntdTheme(compact?: boolean) {
  const themeSettings = useThemeSettings()

  const colors = useAppSelector(themeColors)

  const { darkMode } = useTheme()

  const antdTheme = getAntdTheme(colors, darkMode, themeSettings.tokens)

  antdTheme.algorithm = [darkMode ? theme.darkAlgorithm : theme.defaultAlgorithm]

  if (compact) {
    antdTheme.algorithm.push(theme.compactAlgorithm)
  }

  return { antdTheme }
}

// 转换 ProColumns
function transformedColumns<T extends DataRow>(columns: ProColumns<T>[], searchFormCols: number): ProColumns<T>[] {
  let maxIndex = 0
  return columns.reduce((result: ProColumns<T>[], column) => {
    column.search = column.search === true
    if (column.valueType === 'indexBorder') {
      column.dataIndex = '_index_'
      column.valueType = 'indexBorder'
      // baseColumn.width = column.width || 48
    }

    maxIndex += column.search === true ? 1 : 0
    if (maxIndex === searchFormCols) {
      // 在插入位置，先添加 spacer，再添加当前元素
      result.push(spacer, column)
    } else {
      result.push(column)
    }
    return result
  }, [])
}

export const useTable = <T extends DataRow>(props: TableProps<T>) => {
  const { antdTheme } = useAntdTheme(props.compact)

  const {
    api,
    title,
    rowKey = 'id',
    border = true,
    columns = [],
    params = {},
    pagination = true,
    searchFormCols = 4
  } = props

  const request: ProTableProps<T, Recordable>['request'] = async ({ current, ...rest }, _sort, _filter) => {
    await waitTime(500)
    const { data } = await api({ pageNo: current, ...rest })

    return {
      success: true,
      data: data.list,
      total: data.total
    }
  }

  const formRef = useRef<ProFormInstance>(undefined)
  const actionRef = useRef<ActionType>(null)

  const PlusTable = memo(() => {
    const [formCollapsed, setFormCollapsed] = useState(true)
    return (
      <ConfigProvider theme={antdTheme}>
        <div className="plus-table">
          <ProTable<T>
            actionRef={actionRef}
            cardBordered={border}
            columns={transformedColumns<T>(columns, searchFormCols)}
            dateFormatter="string"
            defaultSize="small"
            editable={{ type: 'multiple' }}
            formRef={formRef}
            ghost={false}
            headerTitle={title}
            options={{ density: true, fullScreen: true, reload: true, setting: { listsHeight: 400 } }}
            pagination={pagination && { pageSize: 20 }}
            params={params}
            request={request}
            rowKey={rowKey}
            scroll={{ x: '100%', y: '100%' }}
            searchFormRender={(_, dom) => <ProSearchAnimation collapsed={formCollapsed}>{dom}</ProSearchAnimation>}
            tableRender={(_, dom) => <div className="plus-table-container">{dom}</div>}
            rowSelection={{
              alwaysShowAlert: false,
              // 注释该行则默认不显示下拉选项
              selections: [Table.SELECTION_ALL, Table.SELECTION_INVERT],
              defaultSelectedRowKeys: []
            }}
            search={{
              span: 24 / searchFormCols,
              labelWidth: 'auto',
              showHiddenNum: true,
              collapsed: formCollapsed,
              onCollapse: collapsed => setFormCollapsed(collapsed),
              collapseRender: (collapsed, _props, __intl, _hiddenNum) => <CollapseButton collapsed={collapsed} />
            }}
            tableExtraRender={(_, data) => (
              <ACard>
                <ADescriptions column={3} size="small">
                  <ADescriptions.Item label="Row">{data.length}</ADescriptions.Item>
                  <ADescriptions.Item label="Created">Lili Qu</ADescriptions.Item>
                  <ADescriptions.Item label="Association">
                    <a>421421</a>
                  </ADescriptions.Item>
                  <ADescriptions.Item label="Creation Time">2017-01-10</ADescriptions.Item>
                  <ADescriptions.Item label="Effective Time">2017-10-10</ADescriptions.Item>
                </ADescriptions>
              </ACard>
            )}
            toolBarRender={() => [
              <AButton key="button" type="primary">
                新建
              </AButton>
            ]}
          />
        </div>
      </ConfigProvider>
    )
  })

  return [PlusTable, actionRef, formRef] as const
}

```
- antd.scss
```scss
.plus-table {
  width: 100%;
  height: 100%;
  > .ant-pro-table {
    height: 100%;
    display: flex;
    flex-direction: column;
    row-gap: 0.5rem;
    /**
    * 搜索栏 - 添加动画组件包裹它
    */
    > .pro-table-search-animate {
      > .pro-table-search-animate--resize {
        > .ant-pro-table-search {
          margin-block-end: 0;
          .ant-pro-form.ant-form-horizontal.ant-pro-query-filter {
            padding: 1rem;
            .ant-row.ant-row-start.ant-pro-query-filter-row {
              position: relative;
              row-gap: 1rem;
              /** 操作栏绝对定位在右上角 */
              > div:last-child {
                right: 0;
                position: absolute;
                margin-inline-start: unset;
              }
            }
          }
        }
      }
    }
    /** 附加栏 */
    > .ant-pro-table-extra {
      margin-block-end: 0;
    }
    /**
     * 让表格高度自适应
     */
    > .plus-table-container {
      flex: 1;
      min-height: 0;
      .ant-pro-card {
        height: 100%;
        .ant-pro-card-body {
          padding-inline: 16px;
          display: flex;
          flex-direction: column;
          .ant-table-wrapper {
            flex: 1;
            min-height: 0;
            .ant-spin-nested-loading {
              height: 100%;
              .ant-spin-container {
                height: 100%;
                display: flex;
                flex-direction: column;
                .ant-table {
                  flex: 1;
                  min-height: 0;
                  .ant-table-container {
                    height: 100%;
                    display: flex;
                    flex-direction: column;
                    .ant-table-body {
                      flex: 1;
                      min-height: 0;
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

.ant-btn {
  /** 按钮的 loading 图标位置居中，不然会撑开按钮宽 */
  .ant-btn-loading-icon {
    position: absolute;
  }
}


```

- src/pages/(base)/demo/table/index.tsx
```tsx
import type { ProColumns } from '@/features/table'
import type { SystemDictType } from '@/service/api'

import { DatePicker } from 'antd'

import { useTable } from '@/features/table'
import { SystemDictTypeApi } from '@/service/api'
import { DICT_TYPE, getDictOptions } from '@/utils'

const columns: ProColumns<SystemDictType.DictType>[] = [
  { align: 'center', title: '序号', valueType: 'indexBorder', width: 50 },
  { align: 'center', dataIndex: 'id', search: false, title: '字典编号' },
  { dataIndex: 'name', search: true, title: '字典名称' },
  { copyable: true, dataIndex: 'type', ellipsis: true, search: true, title: '字典类型' },
  { dataIndex: 'remark', title: '备注' },
  {
    align: 'center',
    dataIndex: 'status',
    valueType: 'select',
    fieldProps: {
      allowClear: true,
      options: getDictOptions(DICT_TYPE.COMMON_STATUS, 'number')
    },
    render: (_, record) => <DictTag type={DICT_TYPE.COMMON_STATUS} value={record.status} />,
    search: true,
    title: '状态'
  },
  {
    dataIndex: 'createTime',
    search: true,
    title: '创建时间',
    valueType: 'dateTime',
    renderFormItem: () => {
      return <DatePicker.RangePicker />
    }
  }
]

const Component = () => {
  const [PlusTable] = useTable<SystemDictType.DictType>({
    api: SystemDictTypeApi.getDictTypePage,
    columns,
    title: '字典类型列表'
  })

  return (
    <PageLayout>
      <PlusTable />
    </PageLayout>
  )
}

export default Component

```

## 另外
### rowSelection 问题

-  alert 区域 能不能显示在 A，B，C，D所在位置，现在显示在一个新行，那么 table 就会少显示一行
- 当然好象可以又来个 自定义的 render 实现 
<img width="1497" alt="Image" src="https://github.com/user-attachments/assets/f0dc31a5-27a5-4d67-acfc-227a475bf1f7" />

### 主题 和 defaultSize 问题

- theme 好象只会对 table 应用 compactAlgorithm，form 或者 card并不受控制？
  ```js
  <ConfigProvider theme={{algorithm: [theme.compactAlgorithm]}}>
  <ProTable .... />
  </ConfigProvider>
  ```
- defaultSize 也不会控制到  form、table 外层的 card 的 padding
- 这显然不是我们期望的效果
- 我的理解 size 应该是控制 ProTable 内的所有组件，而非单单 table，要么就加个 globalSize 控制 gap、padding 和 table的 size?
